### ISSUE TITLE
New page not in UAT

### ISSUE THREAD

**Issue by kcopas** [gbif/alliance#12]
@MortenHofft can you help me? I'm guessing it's some odd character or line break, but I've created a new page that isn't showing up on UAT.

I believe (obviously mistakenly) that this page:
https://github.com/gbif/alliance/tree/master/content/04-Blog/04-global-south

should by all rights appear here:
https://uat.biodiversityinformatics.org/en/blog/global-south

But I'm getting a 404. A little help, por favour?

**Comment by MortenHofft** [comment]
Nothing to do with content changes, Jenkins have changed a bit so the hook doesn't work.

**Comment by MattBlissett** [comment]
Jenkins fixed.

**Comment by kcopas** [comment]
but not working on a new build (sorry):
https://github.com/gbif/alliance/settings/hooks/23330073

**Comment by MortenHofft** [comment]
The jenkins name had changed to allience. I have updated github to match it
