### ISSUE TITLE
remove redirects

### ISSUE THREAD

**Issue by kcopas** [gbif/alliance#16]
Our rollback missed the fact that our change of domains had us redirecting some page URLs here to the allianceforbio domain. As a result, many/most of the pages in the navigation cause 404 errors (they're looking for pages at allianceforbio.org, which is now on Wix with a different URL structure).

When you have a mo, @MattBlissett could you remove the redirects in the batch config (or wherevs) so that the "what's old is new" navigation works?

**Comment by MattBlissett** [comment]
Where should the menu items go instead?

i.e. where do https://www.biodiversityinformatics.org/en/conference, https://www.biodiversityinformatics.org/en/programme etc need to go?

**Comment by MattBlissett** [comment]
Ah, I understand now. Done.

**Comment by kcopas** [comment]
huzzah!
